version: "3.9"

services:
  app:
    build: .
    container_name: task-manager-app
    depends_on:
      - db
      - redis
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: test
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
      DB_HOST: db
      DB_PORT: "5432"

  db:
    image: postgres:15
    container_name: task-manager-db
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: task-manager-redis
    ports:
      - "6379:6379"

volumes:
  db-data: