spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: 3xp3r13nc3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: 3xp3r13nc3
    baseline-description: "init"
    baseline-version: 0